---
title: "Results analysis"
---
```{r}
try({setwd(mainDir)})
mainDir<-getwd()
subDir<-"QSlinks_simple"
#dir.create(file.path(mainDir, subDir))
  
resultDir<-"ACEREBOUT"
setwd(resultDir)
setwd(file.path(mainDir, resultDir))


  
require(readr)
QSlink3ACE <- read_csv("outQSlink3ACEREBOUTwindowsx64.csv")
#summary(QSlink3ACE[,1:30])
require(data.table)
DF<-as.data.table(QSlink3ACE)
#str(DF)
```
sections started
```{r}
imperfect<-DF$algomodel=="perfect"
names(DF)
DF[,keyRedun:=paste0(transTarg,task,transform,pc,expirament,fold)]
Perf<-DF[imperfect,]
DF<-DF[-imperfect,]
summary(Perf[,1:20])

if(F){ #transtarg1 causes utrans to get numbers other than 0
P1<-Perf[RMSEutrans>=4,]
P2<-Perf[RMSEutrans<=4,]
summary(P1[,1:30])
summary(P2[,1:30])
}

Perf[,.N,by=fold]
if(F){ #fold changes max possible but rarely!?
for(i in c(1:4)){
print(summary(Perf[Perf$fold==i,c(1:30),with=FALSE]))
} }

summary(Perf[,.(seed,seedit,foldseed)])

Explosion<-1
for(i in which(names(Perf) %in% c("transTarg","task","transform","pc","expirament","fold"))){
  Explosion<-Explosion * dim(unique(Perf[,(i),with=F]))[1]
  print(Explosion)
}
length(unique(Perf$keyRedun))
length(Perf$keyRedun)/length(unique(Perf$keyRedun))
Perf[,.N,by=keyRedun]
```

NAs removed
```{r}

eh<-is.na(DF[,])
much<-apply(eh,2,sum)
uncol<-which(much>(dim(eh)[1])*.9)
useb<-setdiff(c(1:40),c(uncol[uncol<=40]))
zho<-apply(eh[,useb],1,any)
```





 
 